### ISSUE TITLE
Remove second from the set title

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#113]
If you chose to add time it shows second as well. can you remove it?
![25](https://github.com/thomasdilts/churchsongs/assets/126695454/f790124e-1e86-4c27-9f17-4a1700a9eba6)

**Comment by thomasdilts** [comment]
Fixed. Well, sort of. Ahhh actually not at all.
Unfortunately, getting rid of the seconds is not possible when you choose to do things "internationally."
 However, I have "localized" all showings of the date so that it shows the way arabic speakers expect. That is much better than just getting rid of a pair of zeros.
