### ISSUE TITLE
Verification page in Webiste

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#114]
Malek and I were examining this page and noticed that the system occasionally doesn’t handle deep links as anticipated within the application. Specifically, the verification link sent via email doesn’t redirect the user to the app as it should.

As a temporary solution, we’re considering adding a message to this page instructing users to return to the app. This message would not include any redirection to the website’s homepage or any buttons that might lead the user to other pages on the site.

The proposed message is: “Your account has been activated. Please reopen Zamar and log in using your email and password.”

Blessings.

**Comment by thomasdilts** [comment]
I understand the theory here. BUT this solution suggests that the app is the ONLY part of the zamar system.  There is a web part as well that we can't just hope it disappears.  We need to acknowledge the existence of a web as well. Therefore, my solution I propose is to add your suggested message to the already existing verification page. Perhaps modify your message as the following:

> Your account has been activated. If you are using the Zamar app then please return to the app and log in with your email and password

**Comment by thomasdilts** [comment]
That way it even informs web-users about the existence of an app that perhaps they didn't notice before. Also it shows app users the existence of a web interface. Isn't this the best solution??

**Comment by thomasdilts** [comment]
Fixed. I think my solution is best.

**Comment by MalekBakary** [comment]
I agree that you solution is very good, specially that we inform the users about both the web and the app.
The solution that Elias was suggesting is something temporary until we have the website ready. If you remember i told you about the plan to lunch the app soon and wait with the website lunch until it is ready. Because in the meantime we don't want any one to see the website. So can you please block it temporarily?
