### ISSUE TITLE
Old view still exist!

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#121]
If you press in any shared set link on browser, it takes you to the old view of the website. It can be something you forgot to change when you changed to the new view. 

This is a link to test with:
https://jesusislord.se/zamar/frontend/web/index.php?r=list%2Fsharestartuse&token=UE6wXmkMICQt4HYZA-pBUWWiQ3idG7fm_1697408403

![29](https://github.com/thomasdilts/churchsongs/assets/126695454/7b74f120-bcff-4a28-ab10-7a8bb59c2254)

**Comment by thomasdilts** [comment]
Please test this. It really should be fixed

**Comment by thomasdilts** [comment]
Now I am sure it is fixed

**Comment by thomasdilts** [comment]
You cheated. You used an old link that you got before I made the changes. Now I have deleted all your old shares and they won't work if you try to cheat again. Create a new share and try it. You will never be able to find this view. I know that because nowhere in the code is the expression list%2Fsharestartuse which you see in your link you sent me.

**Comment by MalekBakary** [comment]
That's right, I was cheating without knowing 😂
