### ISSUE TITLE
Comment not accepting emojis

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#126]
I know it is unlikely to add emojis to a comment. But in case anyone do it. We don't want them to see this message 😉

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\xA5\xB3' for column `zamar`.`list_songs`.`notes` at row 1
The SQL being executed was: INSERT INTO `list_songs` (`orderof`, `notes`, `sequence`, `user_lists_id`, `keynote`) VALUES ('Test', 'hiii 🥳', 3, 254, 'Comment,ar')

**Comment by thomasdilts** [comment]
This problem is only on jesusislord.se. Something is wrong with the database there. But on zamarapp.com its works fine. Feel free to test. HOWEVER, note that an emoji is dependent on what font you use. So you will be able to get the emoji into the database on zamarapp.com but it probably won't be visible later when you show it on the screen. There is a small chance we can fix it with using different fonts..
