### ISSUE TITLE
Page 404

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#14]
I have a song that is strange. ID:13
It looks like change request but when I open it I get Page 404. It is not possible to delete it as well.

**Comment by thomasdilts** [comment]
Ok now I have fixed it. The id was NOT 13 but 154. Please look at the real ID column and not the # column to get the id number. Anyway. I deleted this repeated item. I don't know how it happened but it was a change request on something that no longer existed. If it happens again maybe we can find out what the cause was
