### ISSUE TITLE
Key sorting

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#25]
C
Am
C#(or Db)
A#m(Bbm)
D
Bm
D#(Eb)
Cm
E
C#m
F
Dm
F#(Gb)
D#m(Ebm)
G
Em
G#(Ab)
Fm
A
F#m
A#(Bb)
Gm
B
G#m(Abm)

**Comment by thomasdilts** [comment]
This is done now as the default sort. But I still think this is crazy because you can change the keynote yourself for each song.

**Comment by eliasalbro95** [comment]
I believe we have a bug here in the order of the chords and it's my fault.
in this picture, the Dbm is at the end of the list when I'm sorting by Keynote and DESC, but it (Dbm) should be in the same order as the (C#m) because they are the same chord. 
and one more chord I missed in the previous list is (Gbm) and it should be in the same order as the (F#m) and again it's the same chord.
to summarize it:
C
Am
C#(or Db)
A#m(Bbm)
D
Bm
D#(Eb)
Cm
E
**C#m(Dbm)**
F
Dm
F#(Gb)
D#m(Ebm)
G
Em
G#(Ab)
Fm
A
**F#m(Gbm)**
A#(Bb)
Gm
B
G#m(Abm)
![image](https://github.com/thomasdilts/churchsongs/assets/69464989/0454c528-1575-416e-8d33-bb5fbec6829c)

**Comment by thomasdilts** [comment]
Fixed sorting
