### ISSUE TITLE
When I make a change request it not be auto confirmed neither can I manually confirm it

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#51]
It became a only view song. Se the song with ID:
635
639
650
676
665
660
714
704

**Comment by thomasdilts** [comment]
They are all fixed now. The problem was that the column song_change_id was NOT null like it should be. I set song_change_id to null on all of these. Can you tell me the steps I need to do to repeat this bug. That is to make a song stuck in this problem with song_change_id not null?  Was it possibly the app that did this???? This WILL happen again if you cannot tell me the steps to create this problem

**Comment by thomasdilts** [comment]
found the bug. now it is fixed .. you can do your work..
