### ISSUE TITLE
Add Capo to the songs

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#56]
Maybe it is time now to do it :)

**Comment by thomasdilts** [comment]
nope. not time yet. this needs to wait until we get the website looking something like what you want it to look like.

**Comment by MalekBakary** [comment]
@eliasalbro95  is working on it, and he will come back to you soon. He is a musician. I don't have no idea either 🙃

**Comment by eliasalbro95** [comment]
Tomorrow I'll send a brief summary about what is it and how we can implement it. It's not complicated.

**Comment by thomasdilts** [comment]
I know this is something you wanted to do for a long time but don't you think this would be better in the next version? Shouldn't we focus now on just getting something finished that people can use instead of doing a bunch of features that may or may not ever get used?

I think we should instead focus on testing, bug fixing and deployment.

**Comment by eliasalbro95** [comment]
I agree, it needs a bunch of changes in both the back-end and front-end, and it can be postponed wait I think.
@MalekBakary what do you say?

**Comment by MalekBakary** [comment]
Let's make it in the second release 👍
