### ISSUE TITLE
List Add: Time accepts AM/PM

### ISSUE THREAD

**Issue by eliasalbro95** [thomasdilts/churchsongs#66]
Can we modify the time to accept AM/PM? In the current situation it doesn't allow me to add anything but date and time data type, I get this error:
`{name: Database Exception, message: SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '2023-06-30 6:30 م' for column `zamar`.`user_lists`.`custom_date` at row 1`

**Plus**, if we could remove the seconds from the time.

**Comment by thomasdilts** [comment]
Why can't you just enter the international format for time and date? For example 2023-06-28 17:45:00?  If you really must use Am/pm then there are a million functions out there to convert between the two formats. I prefer you do the converting yourself rather than me doing the converting.

**Comment by thomasdilts** [comment]
Yes! I understand. I may need in the future to handle other datetime formats in the web interface. However I still think it's smarter to keep the backend on one single format. Otherwise I would need to have a second field in the backend specifying what format the datetime is in. That would be silly. Much better to keep the backend in one standard format, of course the international one. Am/pm is a crazy American usage anyway. Why would anyone want that as the standard??

**Comment by MalekBakary** [comment]
The Arab world is not much smarter than Americans; they only use the am/pm format. I think, as you do Thomas, that the international format is much better. However, at the same time, I understand what Elias wants because it would be strange for Arab people to see 18:00 as a time 😂. Anyway, I spoke to Elias, and he told me that he can make it appear according to the user's mobile system. For example, if the user has the international time format on their mobile, it will show like that; otherwise, it will show the other way.

**Comment by eliasalbro95** [comment]
Haha, finally the Arab has something in common with the Americans 😂
Okay, then I'll close this one issue.
