### ISSUE TITLE
Text wrap, can we have it when the text is too long?

### ISSUE THREAD

**Issue by MalekBakary** [thomasdilts/churchsongs#80]
![19](https://github.com/thomasdilts/churchsongs/assets/126695454/fd419c4f-ffa1-4643-a713-cf09ac73f5e2)

**I added, 
inline-size: 280px

But it pushed down every thing. se pic 2**

![20](https://github.com/thomasdilts/churchsongs/assets/126695454/8be1a217-570a-4238-a076-fefa74a8e063)

**Comment by thomasdilts** [comment]
Personally I think this is unnecessary. There is no solution that looks better. It's not because we don't know how to do it. I can do any solution your heart desires. The problem is that there is no space and if we make space everything will look worse. You must let go of this. This will end up being like the slider. A total waste of time for nothing at all.

**Comment by MalekBakary** [comment]
My whole idea is to make the text smaller and not change anything with the spaces. 

We can let it be for now, maybe we can do it in the second release.
